GET http://localhost:3000/tasks/2

###
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "sifghweiwey",
  "description": "ajsdfnasdn"
}

###
GET http://localhost:3000/tasks/7a8ecfdc-9dbb-4f61-b707-973f9fc80e61

###
DELETE http://localhost:3000/tasks/5

###
PATCH http://localhost:3000/tasks/86c74863-31f4-4836-baa3-8647fe44ff8c/status
Content-Type: application/json

{
  "status": "TEST"
}