GET http://localhost:3000/tasks

###
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "asdfj",
  "description": "sdfsdfwdsf"
}

###
GET http://localhost:3000/tasks/7a8ecfdc-9dbb-4f61-b707-973f9fc80e61

###
DELETE http://localhost:3000/tasks/6d1ae383-61b0-49a8-8fcc-26fac672bcc1
###
PATCH http://localhost:3000/tasks/86c74863-31f4-4836-baa3-8647fe44ff8c/status
Content-Type: application/json

{
  "status": "TEST"
}